### ISSUE TITLE
Flickering bug in SafeAreaView with enabled new architecture

### ISSUE THREAD

**Issue by iam047** [AppAndFlow/react-native-safe-area-context#586]
### Description

In an empty project with the new architecture enabled, there's an flickering caused by SafeAreaView. However, if you use the useSafeAreaInsets hook for the same purpose, this issue does not occur. Disabling the new architecture also resolves the problem. The same behavior is observed in the latest version (5.2.0).

It appears to be a similar issue to the one described here: [AppAndFlow/react-native-safe-area-context#556](https://github.com/AppAndFlow/react-native-safe-area-context/issues/556).

Please watch the attached video for more details!

https://github.com/user-attachments/assets/95c5537b-8d32-4419-9ad1-aa91db570f17

## Short Reproduction Steps with `react-native-safe-area-context`

1. **Enable New Architecture** 

2. **Add a `SafeAreaView`**  
   ```js
   import { SafeAreaView } from "react-native-safe-area-context";

   export default function HomeScreen() {
     return (
       <SafeAreaView style={{ flex: 1 }}>
         {/* Your content */}
       </SafeAreaView>
     );
   }

3. **Run the app and restarting the app and in some cases you will see the flickering problem like in the video** 
4. **Replace `SafeAreaView` with the `useSafeAreaInsets` hook**  
   ```js
   import { View } from "react-native";
   import { useSafeAreaInsets } from "react-native-safe-area-context";

   export default function HomeScreen() {
     const insets = useSafeAreaInsets();

     return (
       <View
         style={{
           flex: 1,
           paddingTop: insets.top,
           paddingBottom: insets.bottom,
           // Optional: paddingLeft: insets.left, paddingRight: insets.right
         }}
       >
         {/* Your content here */}
       </View>
     );
   }
Re-run the app. The flickering issue should no longer appear.

5. **Enable New Architecture** 
Re-run the app to confirm the issue disappears when the new architecture is off.

### Snack or a link to a repository

https://github.com/iam047/myApp1

### Safe Area Context version

4.12.0

### React Native version

0.76.7

### Platforms

iOS, Android

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16 Pro Max(18.2)

### Acknowledgements

Yes

**Comment by jacobp100** [comment]
[useSafeAreaInsets Docs](https://github.com/AppAndFlow/react-native-safe-area-context?tab=readme-ov-file#usesafeareainsets)

> Note that insets are not updated synchronously so it might cause a slight delay for example when rotating the screen.

https://github.com/AppAndFlow/react-native-safe-area-context?tab=readme-ov-file#optimization

**Comment by iam047** [comment]
Sorry, I forgot to mention that this also happens with `<SafeAreaProvider initialMetrics={initialWindowMetrics}>`.

**Comment by jacobp100** [comment]
Could you log what you actually get for the initial metrics? It's possible it has the wrong values, and it's only once the provider is mounted that the values are corrected - which would cause a flicker

**Comment by iam047** [comment]
Sure! These look correct, and the `useSafeAreaInsets` hook also provides the same inset values.

<img width="1143" alt="Image" src="https://github.com/user-attachments/assets/2a4ce0aa-d1ba-4a1a-ae10-62778bd0132e" />

Or if you mean something else, please provide some steps for me to follow to check it.

**Comment by jacobp100** [comment]
Inside each `<Stack.Screen>` route, you may need to add the `SafeAreaProvider` again because the insets change

**Comment by iam047** [comment]
Hmm, I tried that approach, but unfortunately, it didn’t help—I’m still experiencing the same flickering issue. Wrapping each `<Stack.Screen>` with a `SafeAreaProvider` feels cumbersome and might introduce additional complexity.

**Comment by jacobp100** [comment]
I can't immediately see why you'd see flickering. The SafeAreaProvider is required to hook into the iOS safe area APIs, and is required inside each view controller (i.e. any screen stack, tab bar, modal, and also the top-level app)

**Comment by pshomov** [comment]
I just enabled Fabric on our Expo mobile app, using RN 0.77.1, and am also seeing this. Since we have the exact same set of dependencies on dev and prod (Fabric enabled on dev only) we can see the difference in behaviour. Let me know if there is anything we can contribute to support fixing this issue.

**Comment by jacobp100** [comment]
Are either of you able to reproduce this without react-native-navigation?

I missed that dependency in the original issue, but we get a lot of bugs from people using that library, because they don’t use our library correctly

In particular, they’re passing in safe area insets of zero as the default. Normally rendering is deferred until we have actual insets, but the passing of these explicit zero insets stops that, and it will immediately render everything with those zero insets. Then once everything has been rendered, the actual insets will come in and the layout will update. That’s the cause of your flicker

https://github.com/react-navigation/react-navigation/blob/main/packages/bottom-tabs/src/views/BottomTabView.tsx#L216

I’m 99% sure it’s their issue, so I’m going to close this - because they need to do the fix. But if you are able to reproduce it without them as a dependency I’ll happily reopen the issue

**Comment by aLemonFox** [comment]
I'm not sure what to do with this issue. Could we re-open this issue @jacobp100? I am not using `useSafeAreaInsets`, only `SafeAreaView` with `initialMetrics={initialWindowMetrics}`.

In react-navigation repo, they have a repro to show this is not a react-navigation issue, as it also exists without react-navigation:
https://github.com/react-navigation/react-navigation/issues/12445

**Comment by jacobp100** [comment]
@aLemonFox I can't reproduce this at all. Maybe it's worth taking things out - can you reproduce without Expo and react-native-paper? We have the examples in this repo - they work and they don't have this behaviour

**Comment by aLemonFox** [comment]
Hi @jacobp100, here is a working repro for both Expo and a bare react native project on iOS:
https://github.com/aLemonFox/safearea-repro

As you can see the flicker happens because the top offset is being changed from `8` to `55`. It seems to work only on a real device, as I could not get the alert to work on the simulator.

<img src="https://github.com/user-attachments/assets/b480a177-63fe-44b2-af50-532b8287d8f2" height="720">

**Comment by emanwill** [comment]
Can this please be reopened? We're experiencing this same bug ourselves. We're not using React Navigation. We are using useSafeAreaInsets, not the SafeAreaView component. The bug happens intermittently, and we've only been able to reproduce it so far on Android 14. We're currently on react-native-safe-area-context version 5.4.0.
